#!/usr/bin/env bash
set -euo pipefail

# OpenGPU Relay Configuration Script for OpenClaw
# This script configures OpenClaw to use OpenGPU Network's Relay API

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
CONFIG_DIR="${OPENCLAW_CONFIG_DIR:-$HOME/.openclaw}"
CONFIG_FILE="$CONFIG_DIR/openclaw.json"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

print_header() {
    echo -e "${BLUE}╔════════════════════════════════════════╗${NC}"
    echo -e "${BLUE}║   OpenClaw + OpenGPU Relay Setup      ║${NC}"
    echo -e "${BLUE}╚════════════════════════════════════════╝${NC}"
    echo ""
}

print_success() {
    echo -e "${GREEN}✓ $1${NC}"
}

print_error() {
    echo -e "${RED}✗ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠ $1${NC}"
}

print_info() {
    echo -e "${BLUE}ℹ $1${NC}"
}

# Check if .env file exists
check_env_file() {
    if [[ -f "$PROJECT_ROOT/.env" ]]; then
        if grep -q "OPENGPU_API_KEY" "$PROJECT_ROOT/.env" 2>/dev/null; then
            print_success "OpenGPU API key found in .env file"
            return 0
        fi
    fi
    return 1
}

# Validate OpenGPU API key
validate_opengpu_key() {
    local api_key="$1"

    print_info "Validating OpenGPU API key..."

    if curl -s -f \
        -H "Authorization: Bearer $api_key" \
        "https://relay.opengpu.network/v1/models" >/dev/null 2>&1; then
        print_success "OpenGPU API key is valid!"
        return 0
    else
        print_error "Invalid OpenGPU API key"
        return 1
    fi
}

# Prompt for OpenGPU API key
prompt_api_key() {
    while true; do
        echo -n "Enter your OpenGPU Relay API Key (from https://relaygpu.com): "
        read -rs OPENGPU_API_KEY
        echo ""

        if [[ -z "$OPENGPU_API_KEY" ]]; then
            print_error "API key cannot be empty"
            continue
        fi

        if validate_opengpu_key "$OPENGPU_API_KEY"; then
            break
        fi

        print_warning "Would you like to try again? (y/n)"
        read -r retry
        if [[ "$retry" != "y" && "$retry" != "Y" ]]; then
            return 1
        fi
    done

    return 0
}

# Select default model
select_model() {
    echo ""
    print_info "Select your default model:"
    echo "  1) gpt-oss-120b (120B parameters, powerful but slower) - Recommended"
    echo "  2) gpt-oss-20b  (20B parameters, faster and cheaper)"
    echo "  3) llama-3.2-3b (3B parameters, fastest and cheapest)"
    echo "  4) deepseek-r1-8b (8B parameters, reasoning-focused)"

    while true; do
        echo -n "Enter choice (1-4) [1]: "
        read -r choice
        choice=${choice:-1}

        case $choice in
            1)
                DEFAULT_MODEL="opengpu/openai/gpt-oss-120b"
                break
                ;;
            2)
                DEFAULT_MODEL="opengpu/openai/gpt-oss-20b"
                break
                ;;
            3)
                DEFAULT_MODEL="opengpu/llama-3.2-3b"
                break
                ;;
            4)
                DEFAULT_MODEL="opengpu/deepseek-r1-8b"
                break
                ;;
            *)
                print_error "Invalid choice. Please enter 1-4"
                ;;
        esac
    done

    print_success "Selected: $DEFAULT_MODEL"
}

# Create or update .env file
update_env_file() {
    local env_file="$PROJECT_ROOT/.env"

    if [[ -f "$env_file" ]]; then
        # Backup existing .env
        cp "$env_file" "${env_file}.backup.$(date +%s)"
        print_info "Backed up existing .env file"
    fi

    # Ensure OPENGPU_API_KEY is set
    if ! grep -q "OPENGPU_API_KEY" "$env_file" 2>/dev/null; then
        echo "OPENGPU_API_KEY=$OPENGPU_API_KEY" >>"$env_file"
    else
        # Update existing key
        sed -i.bak "s/^OPENGPU_API_KEY=.*/OPENGPU_API_KEY=$OPENGPU_API_KEY/" "$env_file"
        rm -f "${env_file}.bak"
    fi

    print_success "Updated .env file with OpenGPU API key"
}

# Create OpenClaw configuration with OpenGPU
create_openclaw_config() {
    local config_dir="$CONFIG_DIR"
    local config_file="$config_dir/openclaw.json"

    mkdir -p "$config_dir"

    print_info "Creating OpenClaw configuration..."

    cat >"$config_file" <<EOF
{
  // OpenClaw + OpenGPU Relay Configuration
  // Generated by configure-opengpu.sh

  identity: {
    name: "Clawd",
    theme: "helpful assistant",
    emoji: "🦞",
  },

  // OpenGPU Relay API Configuration
  env: {
    OPENGPU_API_KEY: "${OPENGPU_API_KEY}",
  },

  // Agent configuration with OpenGPU model
  agents: {
    defaults: {
      model: {
        primary: "${DEFAULT_MODEL}",
      },
      // Security: Sandbox all tool execution
      sandbox: {
        mode: "all",
        scope: "agent",
        workspaceAccess: "none",
      },
      // Security: Require human approval for dangerous tools
      tools: {
        confirm: "always",
      },
      // Security: DM policy - pairing required by default
      dmPolicy: "pairing",
      workspace: "~/.openclaw/workspace",
    },
  },

  // Channel configurations
  channels: {
    telegram: {
      // Users must be approved before they can DM (if bot token is set)
      dmPolicy: "pairing",
    },
    discord: {
      dmPolicy: "pairing",
    },
    whatsapp: {
      // WhatsApp users must be approved
      dmPolicy: "pairing",
    },
  },

  // Gateway settings
  gateway: {
    mode: "local",
    bind: "lan",
    port: 18789,
  },

  // Logging
  logging: {
    level: "info",
    consoleLevel: "info",
    consoleStyle: "pretty",
    redactSensitive: "tools",
  },
}
EOF

    print_success "Created OpenClaw configuration at $config_file"
}

# Main menu
show_menu() {
    echo ""
    echo "OpenGPU Relay Configuration Menu:"
    echo "  1) Configure OpenGPU API key"
    echo "  2) Select default model"
    echo "  3) View current configuration"
    echo "  4) Test OpenGPU connection"
    echo "  5) Remove OpenGPU configuration"
    echo "  6) Exit"
    echo ""
}

# Test OpenGPU connection
test_connection() {
    local env_file="$PROJECT_ROOT/.env"
    local api_key=""

    if [[ -f "$env_file" ]]; then
        api_key=$(grep "^OPENGPU_API_KEY=" "$env_file" 2>/dev/null | cut -d'=' -f2)
    fi

    if [[ -z "$api_key" ]]; then
        print_error "No OpenGPU API key found. Please configure it first (option 1)."
        return 1
    fi

    print_info "Testing OpenGPU Relay connection..."

    if curl -s -f \
        -H "Authorization: Bearer $api_key" \
        "https://relay.opengpu.network/v1/models" | jq '.' 2>/dev/null; then
        print_success "OpenGPU Relay connection successful!"
        return 0
    else
        print_error "Failed to connect to OpenGPU Relay"
        return 1
    fi
}

# View current configuration
view_config() {
    local config_file="$CONFIG_FILE"

    if [[ -f "$config_file" ]]; then
        print_info "Current OpenClaw configuration:"
        echo ""
        cat "$config_file" | jq '.' 2>/dev/null || cat "$config_file"
    else
        print_warning "No OpenClaw configuration found at $config_file"
    fi
}

# Remove OpenGPU configuration
remove_config() {
    print_warning "This will remove OpenGPU configuration from:"
    echo "  - $PROJECT_ROOT/.env"
    echo "  - $CONFIG_FILE"
    echo ""
    echo -n "Are you sure? (y/n): "
    read -r confirm

    if [[ "$confirm" == "y" || "$confirm" == "Y" ]]; then
        if [[ -f "$PROJECT_ROOT/.env" ]]; then
            sed -i.bak '/OPENGPU_API_KEY/d' "$PROJECT_ROOT/.env" 2>/dev/null || true
            rm -f "${PROJECT_ROOT}/.env.bak"
            print_success "Removed OpenGPU API key from .env"
        fi

        if [[ -f "$CONFIG_FILE" ]]; then
            rm -f "$CONFIG_FILE"
            print_success "Removed OpenClaw configuration file"
        fi

        print_info "You can now reconfigure OpenClaw with ./docker-setup.sh"
    else
        print_info "Operation cancelled"
    fi
}

# Main function
main() {
    print_header

    # Check dependencies
    if ! command -v docker >/dev/null 2>&1; then
        print_error "Docker is not installed. Please install Docker first."
        exit 1
    fi

    if ! command -v curl >/dev/null 2>&1; then
        print_error "curl is not installed. Please install curl first."
        exit 1
    fi

    print_info "OpenClaw + OpenGPU Relay Configuration"
    print_info "This will configure OpenClaw to use OpenGPU Network's Relay API"
    echo ""

    # Check if already configured
    if check_env_file; then
        print_success "OpenGPU is already configured!"
        echo ""
        echo "What would you like to do?"
        echo "  1) Reconfigure OpenGPU (update API key/model)"
        echo "  2) View current configuration"
        echo "  3) Exit"
        echo ""
        echo -n "Enter choice [3]: "
        read -r initial_choice
        initial_choice=${initial_choice:-3}

        case $initial_choice in
            1)
                # Continue to main configuration flow
                ;;
            2)
                view_config
                exit 0
                ;;
            3)
                print_info "Exiting..."
                exit 0
                ;;
            *)
                print_error "Invalid choice"
                exit 1
                ;;
        esac
    fi

    # Configuration flow
    if ! prompt_api_key; then
        print_error "Configuration cancelled"
        exit 1
    fi

    select_model
    update_env_file
    create_openclaw_config

    echo ""
    print_success "OpenGPU Relay configuration complete!"
    echo ""
    echo "Next steps:"
    echo "  1. Run: ./docker-setup.sh"
    echo "  2. OpenClaw will start with OpenGPU as your LLM provider"
    echo ""
    echo "Your default model: $DEFAULT_MODEL"
    echo ""
    print_info "To configure Telegram/Discord/WhatsApp channels:"
    echo "  docker compose run --rm openclaw-cli channels login       # WhatsApp (QR)"
    echo "  docker compose run --rm openclaw-cli channels add --channel telegram --token <token>"
    echo "  docker compose run --rm openclaw-cli channels add --channel discord --token <token>"
}

# Run main if not sourced
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
