# OpenGPU Relay Configuration Script for OpenClaw (Windows/PowerShell)
# This script configures OpenClaw to use OpenGPU Network's Relay API

$ErrorActionPreference = "Stop"

# Get script directory
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectRoot = Split-Path -Parent $ScriptDir
$ConfigDir = if ($env:OPENCLAW_CONFIG_DIR) { $env:OPENCLAW_CONFIG_DIR } else { "$env:USERPROFILE\.openclaw" }
$ConfigFile = Join-Path $ConfigDir "openclaw.json"
$EnvFile = Join-Path $ProjectRoot ".env"

function Print-Header {
    Write-Host @"

========================================
  OpenClaw + OpenGPU Relay Setup
========================================

"@ -ForegroundColor Cyan
}

function Print-Success {
    param([string]$Message)
    Write-Host "✓ $Message" -ForegroundColor Green
}

function Print-Error {
    param([string]$Message)
    Write-Host "✗ $Message" -ForegroundColor Red
}

function Print-Warning {
    param([string]$Message)
    Write-Host "⚠ $Message" -ForegroundColor Yellow
}

function Print-Info {
    param([string]$Message)
    Write-Host "ℹ $Message" -ForegroundColor Cyan
}

function Test-OpenGpuKey {
    param([string]$ApiKey)

    Write-Host "Validating OpenGPU API key..." -ForegroundColor Cyan

    try {
        $headers = @{
            "Authorization" = "Bearer $ApiKey"
        }

        $response = Invoke-RestMethod -Uri "https://relay.opengpu.network/v1/models" `
            -Headers $headers `
            -TimeoutSec 10

        Print-Success "OpenGPU API key is valid!"
        return $true
    }
    catch {
        Print-Error "Invalid OpenGPU API key"
        return $false
    }
}

function Get-OpenGpuApiKey {
    while ($true) {
        $apiKey = Read-Host "Enter your OpenGPU Relay API Key (from https://relaygpu.com)" -MaskInput

        if ([string]::IsNullOrWhiteSpace($apiKey)) {
            Print-Error "API key cannot be empty"
            continue
        }

        if (Test-OpenGpuKey -ApiKey $apiKey) {
            return $apiKey
        }

        $retry = Read-Host "Would you like to try again? (y/n)"
        if ($retry -ne "y" -and $retry -ne "Y") {
            throw "Configuration cancelled"
        }
    }
}

function Select-Model {
    Write-Host @"

Select your default model:
  1) gpt-oss-120b (120B parameters, powerful but slower) - Recommended
  2) gpt-oss-20b  (20B parameters, faster and cheaper)
  3) llama-3.2-3b (3B parameters, fastest and cheapest)
  4) deepseek-r1-8b (8B parameters, reasoning-focused)

"@ -ForegroundColor Cyan

    while ($true) {
        $choice = Read-Host "Enter choice (1-4) [1]"
        $choice = if ([string]::IsNullOrWhiteSpace($choice)) { "1" } else { $choice }

        switch ($choice) {
            "1" { return "opengpu/openai/gpt-oss-120b" }
            "2" { return "opengpu/openai/gpt-oss-20b" }
            "3" { return "opengpu/llama-3.2-3b" }
            "4" { return "opengpu/deepseek-r1-8b" }
            default {
                Print-Error "Invalid choice. Please enter 1-4"
            }
        }
    }
}

function Update-EnvFile {
    param([string]$ApiKey)

    if (Test-Path $EnvFile) {
        # Backup existing .env
        $backupFile = "$EnvFile.backup.$((Get-Date).Ticks)"
        Copy-Item $EnvFile $backupFile
        Print-Info "Backed up existing .env file"
    }

    # Read existing content or create new
    $envContent = if (Test-Path $EnvFile) { Get-Content $EnvFile } else { @() }

    # Remove existing OPENGPU_API_KEY line if present
    $envContent = $envContent | Where-Object { $_ -notmatch "^OPENGPU_API_KEY=" }

    # Add new API key
    $envContent += "OPENGPU_API_KEY=$ApiKey"

    # Write back
    $envContent | Out-File -FilePath $EnvFile -Encoding UTF8

    Print-Success "Updated .env file with OpenGPU API key"
}

function New-OpenClawConfig {
    param(
        [string]$ApiKey,
        [string]$DefaultModel
    )

    if (!(Test-Path $ConfigDir)) {
        New-Item -ItemType Directory -Path $ConfigDir -Force | Out-Null
    }

    Write-Host "Creating OpenClaw configuration..." -ForegroundColor Cyan

    $config = @"
{
  // OpenClaw + OpenGPU Relay Configuration
  // Generated by configure-opengpu.ps1

  identity: {
    name: "Clawd",
    theme: "helpful assistant",
    emoji: "🦞",
  },

  // OpenGPU Relay API Configuration
  env: {
    OPENGPU_API_KEY: "${ApiKey}",
  },

  // Agent configuration with OpenGPU model
  agents: {
    defaults: {
      model: {
        primary: "${DefaultModel}",
      },
      // Security: Sandbox all tool execution
      sandbox: {
        mode: "all",
        scope: "agent",
        workspaceAccess: "none",
      },
      // Security: Require human approval for dangerous tools
      tools: {
        confirm: "always",
      },
      // Security: DM policy - pairing required by default
      dmPolicy: "pairing",
      workspace: "~/.openclaw/workspace",
    },
  },

  // Channel configurations
  channels: {
    telegram: {
      dmPolicy: "pairing",
    },
    discord: {
      dmPolicy: "pairing",
    },
    whatsapp: {
      dmPolicy: "pairing",
    },
  },

  // Gateway settings
  gateway: {
    mode: "local",
    bind: "lan",
    port: 18789,
  },

  // Logging
  logging: {
    level: "info",
    consoleLevel: "info",
    consoleStyle: "pretty",
    redactSensitive: "tools",
  },
}
"@

    $config | Out-File -FilePath $ConfigFile -Encoding UTF8

    Print-Success "Created OpenClaw configuration at $ConfigFile"
}

function Test-Connection {
    if (!(Test-Path $EnvFile)) {
        Print-Error "No .env file found. Please configure OpenGPU first."
        return
    }

    $envContent = Get-Content $EnvFile
    $apiKeyLine = $envContent | Where-Object { $_ -match "^OPENGPU_API_KEY=" }

    if ([string]::IsNullOrWhiteSpace($apiKeyLine)) {
        Print-Error "No OpenGPU API key found in .env file"
        return
    }

    $apiKey = ($apiKeyLine -split "=")[1]

    Write-Host "Testing OpenGPU Relay connection..." -ForegroundColor Cyan

    try {
        $headers = @{
            "Authorization" = "Bearer $ApiKey"
        }

        $response = Invoke-RestMethod -Uri "https://relay.opengpu.network/v1/models" `
            -Headers $headers `
            -TimeoutSec 10

        $response | ConvertTo-Json -Depth 10

        Print-Success "OpenGPU Relay connection successful!"
    }
    catch {
        Print-Error "Failed to connect to OpenGPU Relay: $_"
    }
}

function Show-Config {
    if (Test-Path $ConfigFile) {
        Write-Host "Current OpenClaw configuration:" -ForegroundColor Cyan
        Write-Host ""
        Get-Content $ConfigFile
    }
    else {
        Print-Warning "No OpenClaw configuration found at $ConfigFile"
    }
}

function Remove-Config {
    Write-Host "This will remove OpenGPU configuration from:" -ForegroundColor Yellow
    Write-Host "  - $EnvFile"
    Write-Host "  - $ConfigFile"
    Write-Host ""

    $confirm = Read-Host "Are you sure? (y/n)"

    if ($confirm -eq "y" -or $confirm -eq "Y") {
        if (Test-Path $EnvFile) {
            $envContent = Get-Content $EnvFile | Where-Object { $_ -notmatch "^OPENGPU_API_KEY=" }
            $envContent | Out-File -FilePath $EnvFile -Encoding UTF8
            Print-Success "Removed OpenGPU API key from .env"
        }

        if (Test-Path $ConfigFile) {
            Remove-Item $ConfigFile -Force
            Print-Success "Removed OpenClaw configuration file"
        }

        Print-Info "You can now reconfigure OpenClaw with .\docker-setup.sh"
    }
    else {
        Print-Info "Operation cancelled"
    }
}

function Show-Menu {
    Write-Host @"

OpenGPU Relay Configuration Menu:
  1) Configure OpenGPU API key
  2) Select default model
  3) View current configuration
  4) Test OpenGPU connection
  5) Remove OpenGPU configuration
  6) Exit

"@ -ForegroundColor Cyan
}

# Main function
function Main {
    Print-Header

    # Check dependencies
    if (!(Get-Command docker -ErrorAction SilentlyContinue)) {
        Print-Error "Docker is not installed. Please install Docker Desktop first."
        exit 1
    }

    Print-Info "OpenClaw + OpenGPU Relay Configuration"
    Print-Info "This will configure OpenClaw to use OpenGPU Network's Relay API"
    Write-Host ""

    # Check if already configured
    $alreadyConfigured = $false
    if (Test-Path $EnvFile) {
        $envContent = Get-Content $EnvFile
        $apiKeyLine = $envContent | Where-Object { $_ -match "^OPENGPU_API_KEY=" }
        if ($apiKeyLine) {
            Print-Success "OpenGPU is already configured!"
            Write-Host ""
            Write-Host "What would you like to do?"
            Write-Host "  1) Reconfigure OpenGPU (update API key/model)"
            Write-Host "  2) View current configuration"
            Write-Host "  3) Exit to menu"
            Write-Host ""

            $initialChoice = Read-Host "Enter choice [3]"
            $initialChoice = if ([string]::IsNullOrWhiteSpace($initialChoice)) { "3" } else { $initialChoice }

            switch ($initialChoice) {
                "1" {
                    # Continue to main configuration flow
                    $alreadyConfigured = $false
                }
                "2" {
                    Show-Config
                    return
                }
                "3" {
                    # Show menu loop
                    $alreadyConfigured = $true
                }
                default {
                    Print-Error "Invalid choice"
                    exit 1
                }
            }
        }
    }

    if ($alreadyConfigured) {
        # Menu loop
        while ($true) {
            Show-Menu
            $choice = Read-Host "Enter choice"

            switch ($choice) {
                "1" {
                    try {
                        $apiKey = Get-OpenGpuApiKey
                        $model = Select-Model
                        Update-EnvFile -ApiKey $apiKey
                        New-OpenClawConfig -ApiKey $apiKey -DefaultModel $model
                        Print-Success "Configuration updated!"
                    }
                    catch {
                        Print-Error "Configuration cancelled: $_"
                    }
                }
                "2" {
                    $model = Select-Model
                    Print-Success "Model selected: $model"
                    Print-Info "Run option 1 to apply this model"
                }
                "3" {
                    Show-Config
                }
                "4" {
                    Test-Connection
                }
                "5" {
                    Remove-Config
                }
                "6" {
                    Print-Info "Exiting..."
                    return
                }
                default {
                    Print-Error "Invalid choice"
                }
            }
        }
    }
    else {
        # First-time configuration flow
        try {
            $apiKey = Get-OpenGpuApiKey
            $model = Select-Model
            Update-EnvFile -ApiKey $apiKey
            New-OpenClawConfig -ApiKey $apiKey -DefaultModel $model

            Write-Host ""
            Print-Success "OpenGPU Relay configuration complete!"
            Write-Host ""
            Write-Host "Next steps:"
            Write-Host "  1. Run: .\docker-setup.sh"
            Write-Host "  2. OpenClaw will start with OpenGPU as your LLM provider"
            Write-Host ""
            Write-Host "Your default model: $model"
            Write-Host ""
            Print-Info "To configure Telegram/Discord/WhatsApp channels:"
            Write-Host "  docker compose run --rm openclaw-cli channels login       # WhatsApp (QR)"
            Write-Host "  docker compose run --rm openclaw-cli channels add --channel telegram --token <token>"
            Write-Host "  docker compose run --rm openclaw-cli channels add --channel discord --token <token>"
        }
        catch {
            Print-Error "Configuration failed: $_"
            exit 1
        }
    }
}

# Run main
Main
